# Generated by Django 5.0.6 on 2024-07-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=60)),
                ('cover_image', models.ImageField(upload_to='')),
                ('summary', models.TextField()),
                ('author_email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.BooleanField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
